### ISSUE TITLE
[OOB 5.4] Online compiler not producing two binaries

### ISSUE THREAD

**Issue by sarahmarshy** [ARMmbed/mbed-os-example-bootloader-blinky#4]
This example compiles two binaries offline: the bootloader combined with the application and application only. The online tools only produce one, the application binary.

@theotherjimmy

**Comment by theotherjimmy** [comment]
Yeah, this is not supported at the moment.

**Comment by 0xc0170** [comment]
> Yeah, this is not supported at the moment.

Worth stating anywhere? Any pointers?

**Comment by MarceloSalazar** [comment]
I'd suggest stating this as a note in the docs of this example

**Comment by 0xc0170** [comment]
@theotherjimmy Can you create a tracking issue for this support in the mbed-os repository (with description) ? Thanks!

**Comment by adbridge** [comment]
@theotherjimmy Discussed this with @sg- , he thinks the online IDE should output the composite binary. Can this be fixed before the 5.4 tools release ?

**Comment by theotherjimmy** [comment]
Yes it should, eventually. I was under the impression that it was not a requirement for 5.4.0.

**Comment by theotherjimmy** [comment]
I can get it in for the 5.4 release online, but that might delay the tools being released to the website by a bit.

**Comment by theotherjimmy** [comment]
I'm thinking it will take a day or two to change the web code and test before it's deployed to production servers. @sg-

**Comment by 0xc0170** [comment]
> I'm thinking it will take a day or two to change the web code and test before it's deployed to production servers. @sg-

Whats the status?

**Comment by sg-** [comment]
Should be resolved once deployed online.
